CREATE TABLE noteful_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT,
  nickname TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ALTER TABLE noteful_notes
--   ADD COLUMN
--     author INTEGER REFERENCES noteful_users(id)
--     ON DELETE SET NULL;