CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    text TEXT NOT NULL,
    date_commented TIMESTAMPTZ DEFAULT now() NOT NULL,
    article_id INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES noteful_users(id) ON DELETE CASCADE NOT NULL
);

TRUNCATE noteful_folders, noteful_users, noteful_notes RESTART IDENTITY CASCADE;